version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
        command: |
          sudo npm install -g npm@latest
          npm install
          npm run test

